# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20170317_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mLike',
            new_name='Like',
        ),
    ]
