# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_remove_image_number_of_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
