# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='coach_name',
            field=models.CharField(default=b'\xd0\xa5\xd0\xb0\xd1\x80\xd0\xbb\xd0\xb0\xd0\xbc\xd0\xbf\xd0\xb8\xd0\xb5\xd0\xb2', max_length=50),
        ),
    ]
