# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_club_coach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
