# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='likes',
            field=models.IntegerField(default=0, verbose_name=b'\xd0\x9d\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb8\xd1\x82\xd1\x81\xd1\x8f'),
        ),
    ]
