# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_club_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_logo',
            field=models.ImageField(blank=True, default=b'', upload_to=b'clubs/photos'),
        ),
        migrations.AlterField(
            model_name='club',
            name='likes',
            field=models.IntegerField(default=0, verbose_name=b'\xd0\x9d\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb8\xd1\x82\xd1\x81\xd1\x8f \xd0\xbb\xd1\x8e\xd0\xb4\xd1\x8f\xd0\xbc'),
        ),
    ]
