# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_auto_20170404_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
